# -*- coding: utf-8 -*-
"""
Genera la versione tedesca del sito (prova/de/index.html) a partire dalla pagina italiana (prova/index.html).

Stesso meccanismo di build_en.py (che contiene il generatore): le coppie sono (testo italiano -> tedesco) e ogni
coppia deve trovare il suo testo nella pagina italiana. Se un testo italiano cambia, va aggiornata la coppia
in build_en.py E in questo file.

Uso (dalla cartella del progetto):
    python tools/build_de.py

Voce: impersonale e precisa, come in italiano; prima persona solo in 'Chi sono' e nei messaggi diretti.
Il modulo usa la forma di cortesia in modo impersonale (niente 'Sie' diretto). Prezzi nel formato tedesco: 1.500 €.
DA FAR RILEGGERE a una persona di madrelingua prima di mostrare la pagina a clienti.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_en as b

OUT = os.path.join(b.ROOT, "prova", "de", "index.html")

TEXT = [
# testata e menu
("Il mestiere", "Das Handwerk"),
("Il metodo", "Die Methode"),
("Le regole", "Die Konditionen"),
("Il prezzo", "Preise"),
("Chi sono", "Über mich"),
("Domande", "FAQ"),
("Richiedi un incontro", "Termin anfragen"),
("Primo incontro", "Erstgespräch"),
# hero
('Progettazione digitale<br class="mb"> per piccole imprese', 'Digitale Gestaltung<br class="mb"> für kleine Betriebe'),
("Soluzioni<br><em>su misura</em>", "Nach<br><em>Maß</em>"),
("Costruzione di siti, menu digitali e automazioni per stabilimenti, ristoranti e piccole attività, con aggiornamenti, modifiche e supporto continuo.", "Websites, digitale Speisekarten und Automatisierungen für Strandbäder, Restaurants und kleine Betriebe, mit laufenden Aktualisierungen, Änderungen und dauerhafter Betreuung."),
("Richiedi il primo incontro", "Erstgespräch anfragen"),
("Un'ora tra chiacchiere e caffè, offerta dallo studio.<br>Di persona (consigliato) o in video.", "Eine Stunde bei Kaffee und Gespräch, vom Studio angeboten.<br>Persönlich (empfohlen) oder per Video."),
("Il mestiere, in quattro parti", "Das Handwerk in vier Teilen"),
("Studio a Cesenatico, con clienti<br>in Romagna e a distanza", "Studio in Cesenatico, mit Kunden<br>in der Romagna und aus der Ferne"),
("Siti, menu digitali, automazioni<br>e assistenza continua", "Websites, digitale Speisekarten, Automatisierungen<br>und laufender Support"),
("Risposte rapide<br>e dirette", "Schnelle,<br>direkte Antworten"),
# costa
("Il mare cambia a ogni stagione, e una presenza online ben tenuta cambia con lui.", "Das Meer verändert sich mit jeder Saison, und ein gepflegter Online-Auftritt verändert sich mit ihm."),
# punto di partenza
("Il punto di partenza", "Der Ausgangspunkt"),
("Quello che succede <em>dopo la consegna</em>", "Was <em>nach der Übergabe</em> geschieht"),
("Costruire richiede settimane. Mantenere richiede anni, ed è la parte che in molti contratti non ha un responsabile.", "Der Aufbau dauert Wochen. Die Pflege dauert Jahre, und in vielen Verträgen ist sie der Teil, für den niemand zuständig ist."),
("Ferma al giorno della consegna", "Stehengeblieben am Tag der Übergabe"),
("Orari, prezzi e offerte cambiano a ogni stagione, quattro volte l'anno, e uno strumento che non cambia con loro smette di dire la verità.", "Öffnungszeiten, Preise und Angebote ändern sich mit jeder Saison, viermal im Jahr, und ein Werkzeug, das sich nicht mit ihnen ändert, sagt bald nicht mehr die Wahrheit."),
("Un canone che non dice cosa copre", "Eine Gebühr, die nicht sagt, was sie abdeckt"),
("Cinquanta euro al mese senza modifiche incluse fanno 600 euro l'anno: conviene sapere con precisione cosa coprono.", "Fünfzig Euro im Monat ohne enthaltene Änderungen sind 600 Euro im Jahr: Es lohnt sich zu wissen, was genau damit abgedeckt ist."),
("Visite che non diventano richieste", "Besuche, die nicht zu Anfragen werden"),
("Si conta quante persone arrivano, quasi mai quante scrivono, telefonano o prenotano, né dove si fermano le altre.", "Gezählt wird, wie viele Menschen kommen, fast nie, wie viele schreiben, anrufen oder buchen, und auch nicht, wo die anderen abspringen."),
# mestiere
("Il mestiere, <em>in quattro parti</em>", "Das Handwerk <em>in vier Teilen</em>"),
("Ogni parte funziona da sola. Si può cominciare da una qualunque, o dalla prima e vedere come va.", "Jeder Teil funktioniert für sich. Man kann mit einem beliebigen beginnen, oder mit dem ersten und sehen, wie es läuft."),
("01 · Sito, menu, schede e profili", "01 · Website, Speisekarte, Einträge und Profile"),
("Presenza online", "Online-Präsenz"),
("Il problema", "Das Problem"),
("Quattro stagioni, quattro aggiornamenti l'anno, ciascuno da ripetere su sito, scheda Google, profili e menu. Ogni copia dimenticata è un'informazione sbagliata.", "Vier Jahreszeiten, vier Aktualisierungen im Jahr, jede auf Website, Google-Eintrag, Profilen und Speisekarte zu wiederholen. Jede vergessene Kopie ist eine falsche Information."),
("La risposta", "Die Antwort"),
("Un punto solo da cui si aggiorna tutto, e una prima risposta entro un giorno lavorativo a ogni richiesta di modifica.", "Ein einziger Ort, von dem aus alles aktualisiert wird, und eine erste Antwort innerhalb eines Werktags auf jede Änderungsanfrage."),
("02 · Risposte, richieste, promemoria", "02 · Antworten, Anfragen, Erinnerungen"),
("Automazioni", "Automatisierungen"),
("Una risposta scritta a mano per cinque minuti al giorno sono più di 30 ore l'anno.",
 "Eine von Hand geschriebene Antwort, fünf Minuten am Tag, sind mehr als 30 Stunden im Jahr."),
("Si individua il compito più ripetuto, lo si cronometra e si costruisce lo strumento che lo fa da solo. Il risultato si confronta con le ore di partenza.",
 "Die am häufigsten wiederholte Aufgabe wird erkannt und gestoppt, dann wird das Werkzeug gebaut, das sie von selbst erledigt. Das Ergebnis wird mit den Ausgangsstunden verglichen."),
("03 · Aggiornamenti, sicurezza, backup", "03 · Updates, Sicherheit, Backups"),
("Cura continua", "Laufende Betreuung"),
("Aggiornamenti, backup e sicurezza si rimandano finché qualcosa smette di funzionare, e a quel punto il costo è quello di un'emergenza, non di una manutenzione.",
 "Updates, Backups und Sicherheit werden aufgeschoben, bis etwas nicht mehr funktioniert, und dann sind die Kosten die eines Notfalls, nicht die einer Wartung."),
("Il primo mese a forfait, senza limite di ore, misura il consumo reale. Dal secondo, un monte ore fissato sui dati raccolti e una prima risposta entro un giorno lavorativo.", "Der erste Monat ist pauschal und ohne Stundenbegrenzung, um den tatsächlichen Verbrauch zu messen. Ab dem zweiten Monat ein Stundenkontingent auf Basis der gesammelten Daten und eine erste Antwort innerhalb eines Werktags."),
("04 · Numeri, percorsi, priorità", "04 · Zahlen, Wege, Prioritäten"),
("Check-up", "Check-up"),
("Prima di spendere in una nuova pagina conviene sapere dove le persone si fermano. Senza questo dato ogni intervento è una scommessa.", "Bevor in eine neue Seite investiert wird, lohnt es sich zu wissen, wo die Menschen abspringen. Ohne diese Zahl ist jeder Eingriff ein Glücksspiel."),
("In tre giorni lavorativi dalla conferma e dalla ricezione degli accessi, un rapporto con la mappa delle priorità, ciascuna con il suo costo. Il costo del check-up si scala dal lavoro che segue.", "Innerhalb von drei Werktagen nach Bestätigung und Erhalt der Zugänge ein Bericht mit der Prioritätenkarte, jede mit ihren Kosten. Die Kosten des Check-ups werden auf die anschließende Arbeit angerechnet."),
("Un messaggio su WhatsApp", "Nachricht per WhatsApp"),
("Scorri per vedere gli altri", "Wischen, um die anderen Leistungen zu sehen"),
("Scorri di lato", "Seitlich wischen"),
# metodo
("Come si lavora", "So wird gearbeitet"),
("Si misura prima <em>di costruire</em>", "Erst messen, <em>dann bauen</em>"),
("Un metodo in quattro tempi, con un risultato chiuso a ogni passo e un numero da cui partire. Il percorso si adatta al servizio scelto.", "Eine Methode in vier Schritten, mit einem abgeschlossenen Ergebnis je Schritt und einer Zahl als Ausgangspunkt. Der Weg passt sich der gewählten Leistung an."),
("Un'ora per capire come si lavora e dove si perde tempo. Si decide insieme quale numero conta (richieste, prenotazioni, iscritti) e da quanto si parte.", "Eine Stunde, um zu verstehen, wie gearbeitet wird und wo Zeit verloren geht. Gemeinsam wird entschieden, welche Zahl zählt (Anfragen, Buchungen, Mitglieder) und von wo aus gestartet wird."),
("Ricerca su ciò che esiste: sito, profili, posta, gestionale, dati. In tre giorni lavorativi dalla conferma e dalla ricezione degli accessi un rapporto con la mappa delle priorità e il costo di ciascuna.", "Recherche zu dem, was bereits besteht: Website, Profile, E-Mail, Verwaltungssoftware, Daten. Innerhalb von drei Werktagen nach Bestätigung und Erhalt der Zugänge ein Bericht mit der Prioritätenkarte und den Kosten jeder einzelnen."),
("Costruzione", "Aufbau"),
("Sviluppo a tappe, con due giri di correzioni e un prezzo chiuso. A ogni tappa si vede qualcosa che funziona.", "Entwicklung in Etappen, mit zwei Korrekturrunden und einem Festpreis. Mit jeder Etappe ist etwas zu sehen, das funktioniert."),
("Cura", "Betreuung"),
("Messa a punto nel tempo: si aggiorna, si regola e si rimisura. Ogni mese un resoconto confronta i numeri con il punto di partenza.", "Feinabstimmung über die Zeit: aktualisieren, justieren, neu messen. Jeden Monat vergleicht ein Bericht die Zahlen mit dem Ausgangspunkt."),
# caso
("Un caso misurato", "Ein gemessener Fall"),
("Ogni obiettivo ha un numero. <em>Si parte da lì</em>", "Jedes Ziel hat eine Zahl. <em>Dort beginnt es</em>"),
("Iscritti, prenotazioni, richieste, ordini: qualunque obiettivo si voglia far crescere, si misura il punto di partenza, si costruisce, si misura di nuovo.", "Mitglieder, Buchungen, Anfragen, Bestellungen: Welches Ziel auch wachsen soll, der Ausgangspunkt wird gemessen, es wird gebaut, dann wird erneut gemessen."),
("Iscritti a una società sportiva", "Mitglieder eines Sportvereins"),
("Primi due anni", "Erste zwei Jahre"),
("Dopo una settimana", "Nach einer Woche"),
("Il primo caso misurato: una società sportiva, da 115 a 450 iscritti in una settimana. Tre gli interventi: correzione nel sito di errori e logiche ormai superate, ricerca e sviluppo di un nuovo metodo di accesso ai palazzetti, traffico online riportato su una pagina ad accesso riservato al posto di servizi di terze parti.", "Der erste gemessene Fall: ein Sportverein, von 115 auf 450 Mitglieder in einer Woche. Drei Eingriffe: Behebung überholter Fehler und Logiken auf der Website, Recherche und Entwicklung eines neuen Zugangsverfahrens für die Sporthallen, und Online-Verkehr auf eine Seite mit eingeschränktem Zugang umgeleitet, anstelle von Diensten Dritter."),
# obiettivi
("Cosa si misura", "Was gemessen wird"),
("I numeri <em>che contano</em>", "Die Zahlen, <em>die zählen</em>"),
("Tre degli obiettivi che le piccole attività inseguono più spesso, e il numero con cui si misura ciascuno.", "Drei der Ziele, die kleine Betriebe am häufigsten verfolgen, und die Zahl, mit der sich jedes messen lässt."),
("Iscritti", "Mitglieder"),
("Nuove iscrizioni e ritorni nel tempo. Nel caso misurato: da 115 a 450 in una settimana.", "Neue Anmeldungen und Wiederkehrer im Zeitverlauf. Im gemessenen Fall: von 115 auf 450 in einer Woche."),
("Prenotazioni", "Buchungen"),
("Richieste di tavolo o di ombrellone arrivate da sito, menu e schede, confrontate prima e dopo il lavoro.", "Tisch- oder Sonnenschirmanfragen über Website, Speisekarte und Einträge, verglichen vor und nach der Arbeit."),
("Richieste", "Anfragen"),
("Messaggi e richieste di preventivo ricevuti, e tempo medio che passa prima di una risposta.", "Eingegangene Nachrichten und Angebotsanfragen sowie die durchschnittliche Zeit bis zu einer Antwort."),
("Un altro obiettivo, o un altro problema? Si racconta qui, e si lavora insieme per risolverlo", "Ein anderes Ziel oder ein anderes Problem? Hier erzählen, und gemeinsam daran arbeiten"),
("Un altro obiettivo? Si racconta qui", "Ein anderes Ziel? Hier erzählen"),
# regole
("Condizioni chiare, <em>scritte prima</em>", "Klare Konditionen, <em>vorab schriftlich</em>"),
("Ciò che è incluso è scritto prima di cominciare.", "Was enthalten ist, steht vor Beginn schriftlich fest."),
("Ascolto", "Zuhören"),
("Un'ora per ascoltare come si lavora e raccogliere i numeri di partenza. Nessuna proposta improvvisata.", "Eine Stunde, um zuzuhören, wie gearbeitet wird, und die Ausgangszahlen zu sammeln. Keine improvisierten Vorschläge."),
("Trasparenza", "Transparenz"),
("Preventivo", "Angebot"),
("Cosa include, quanto costa e in quanto tempo si consegna, tutto scritto prima di cominciare. Il prezzo non cambia in corsa.", "Was enthalten ist, was es kostet und wann geliefert wird, alles schriftlich vor Beginn. Der Preis ändert sich unterwegs nicht."),
("Equità", "Fairness"),
("Il costo del check-up viene scalato dal lavoro che segue, se si prosegue.", "Die Kosten des Check-ups werden auf die anschließende Arbeit angerechnet, wenn es weitergeht."),
("Prontezza", "Schnelligkeit"),
("Risposta", "Antwort"),
("Ogni messaggio riceve una prima risposta entro un giorno lavorativo.", "Jede Nachricht erhält eine erste Antwort innerhalb eines Werktags."),
("Dedizione", "Hingabe"),
("Tempi di consegna", "Lieferzeiten"),
("Il massimo focus su ogni lavoro è garantito: il tempo di consegna è scritto nel preventivo ed è quello che si rispetta.", "Volle Konzentration auf jede Arbeit ist garantiert: Die Lieferzeit steht im Angebot, und sie wird eingehalten."),
("Equilibrio", "Ausgewogenheit"),
("Rodaggio", "Einlaufphase"),
("Il primo mese è a forfait e senza limite di ore, per assistenza, ricerca e idee. A fine mese un resoconto con le ore reali stabilisce quante ne servono.", "Der erste Monat ist pauschal und ohne Stundenbegrenzung, für Support, Recherche und Ideen. Am Monatsende legt ein Bericht mit den tatsächlichen Stunden fest, wie viele benötigt werden."),
# stimatore
("Il prezzo di partenza", "Der Startpreis"),
("Il prezzo, <em>detto prima di cominciare</em>", "Der Preis, <em>vorab genannt</em>"),
("Lo studio lavora da solo e usa strumenti che automatizzano le parti ripetitive: per questo i costi restano contenuti senza ridurre la cura. Il prezzo è scritto prima di decidere.", "Das Studio arbeitet allein und nutzt Werkzeuge, die die wiederkehrenden Teile automatisieren: Deshalb bleiben die Kosten überschaubar, ohne an Sorgfalt zu sparen. Der Preis steht schriftlich fest, bevor entschieden wird."),
("Quattro domande bastano per un prezzo di partenza, subito e senza telefonate.", "Vier Fragen genügen für einen Startpreis, sofort und ohne Telefonate."),
("Tipo di attività", "Art des Betriebs"),
("Stabilimento balneare", "Strandbad"),
("Ristorante o bar", "Restaurant oder Bar"),
("Hotel o struttura ricettiva", "Hotel oder Unterkunft"),
("Negozio o artigiano", "Geschäft oder Handwerksbetrieb"),
("Studio professionale", "Kanzlei oder Praxis"),
("Altro", "Sonstiges"),
("Cosa serve ", "Was benötigt wird "),
("Si può scegliere più di una voce.", "Es kann mehr als eine Option gewählt werden."),
("Un sito", "Eine Website"),
("Un menu digitale", "Eine digitale Speisekarte"),
("Automatizzare una parte del lavoro", "Einen Teil der Arbeit automatisieren"),
("Assistenza continua", "Laufender Support"),
("Da capire: serve un check-up per partire", "Noch unklar: Zum Start braucht es einen Check-up"),
("Presenza online oggi", "Online-Präsenz heute"),
("Nessuna presenza online", "Keine Online-Präsenz"),
("Una presenza vecchia, da rifare", "Eine veraltete Präsenz, die neu gemacht werden muss"),
("Una presenza che nessuno segue", "Eine Präsenz, um die sich niemand kümmert"),
("Una presenza che funziona, serve altro", "Eine funktionierende Präsenz, es braucht etwas anderes"),
("Dimensione del lavoro", "Umfang der Arbeit"),
("Essenziale", "Grundlegend"),
("Poche cose, ben definite.", "Wenige, klar definierte Dinge."),
("Completo", "Umfassend"),
("Più pagine o più passaggi.", "Mehrere Seiten oder mehrere Schritte."),
("Con funzioni", "Mit Funktionen"),
("Iscrizioni, prenotazioni, area riservata o un processo articolato.", "Anmeldungen, Buchungen, ein geschützter Bereich oder ein komplexer Ablauf."),
("Dove inviare il prezzo ", "Wohin der Preis gesendet wird "),
("Nome ed email bastano per vedere subito il prezzo di partenza.", "Name und E-Mail genügen, um sofort den Startpreis zu sehen."),
("Nome", "Name"),
("Email", "E-Mail"),
("Telefono (facoltativo)", "Telefon (optional)"),
("Non compilare ", "Nicht ausfüllen "),
("Ho letto l'", "Zur Kenntnis genommen: die "),
("informativa privacy", "Datenschutzerklärung"),
("Indietro", "Zurück"),
("Avanti", "Weiter"),
("Vedi il prezzo", "Preis ansehen"),
("Prezzo di partenza", "Startpreis"),
("Contattami su WhatsApp", "Per WhatsApp schreiben"),
("Ricomincia", "Neu beginnen"),
# chi sono
("Dalla sala <em>ai dati</em>", "Vom Gastraum <em>zu den Daten</em>"),
("Il mio primo ricordo dei numeri è nel negozio di mia nonna: mentre lavorava, per tenermi occupato mi dava pagine di operazioni da risolvere, a mente o con carta e penna. Trovare il risultato mi dava una sensazione di completezza che non ho mai smesso di cercare. Ancora oggi, davanti a un problema, parto dalla convinzione che una soluzione esista. E quando non la trovo, ho imparato a cambiare prospettiva: forse è la domanda a essere sbagliata.", "Meine erste Erinnerung an Zahlen stammt aus dem Laden meiner Großmutter: Während sie arbeitete, gab sie mir, um mich zu beschäftigen, Seiten mit Rechenaufgaben, die ich im Kopf oder mit Stift und Papier lösen sollte. Das Ergebnis zu finden gab mir ein Gefühl von Vollständigkeit, das ich nie aufgehört habe zu suchen. Noch heute gehe ich bei einem Problem von der Überzeugung aus, dass es eine Lösung gibt. Und wenn ich sie nicht finde, habe ich gelernt, die Perspektive zu wechseln: Vielleicht ist die Frage die falsche."),
("A undici anni facevo caffè in un bar di Cesenatico: asciugare un cestello di bicchieri mi comprava dieci minuti con gli amici. I miei genitori gestivano attività e il lavoro, in casa, faceva parte della vita. Da lì vent'anni nella ristorazione, di cui tredici alla direzione di locali a Sydney. Ho imparato ad affrontare i problemi quando arrivano, perché dopo di te non c'è nessuno: <em>the buck stops with you</em>. E a leggere i numeri per capire cosa funziona, cosa no e dove vale la pena cambiare.", "Mit elf Jahren machte ich Kaffee in einer Bar in Cesenatico: Einen Korb Gläser abzutrocknen kaufte mir zehn Minuten mit Freunden. Meine Eltern führten Betriebe, und Arbeit gehörte zu Hause zum Leben. Von da an zwanzig Jahre Gastronomie, davon dreizehn in der Leitung von Lokalen in Sydney. Ich habe gelernt, Probleme anzugehen, wenn sie kommen, denn nach dir ist niemand mehr da: <em>the buck stops with you</em>. Und die Zahlen zu lesen, um zu verstehen, was funktioniert, was nicht und wo sich eine Veränderung lohnt."),
("Dopo il Covid ho deciso di esserci di più per la mia famiglia, soprattutto per le mie figlie. Sono tornato a studiare, prima finanza, poi matematica e statistica, conseguendo due diplomi mentre continuavo a lavorare. Sono entrato nel mondo dei dati, lavorando per enti pubblici e grandi aziende. Dopo vent'anni di esperienza sono ripartito da principiante, ma non da zero. Mi sono portato dietro la capacità di leggere le persone, di capirle anche senza parole. Una sensibilità che davanti a uno schermo non si impara.", "Nach Covid habe ich beschlossen, mehr für meine Familie da zu sein, vor allem für meine Töchter. Ich habe wieder angefangen zu studieren, zuerst Finanzwesen, dann Mathematik und Statistik, und habe zwei Abschlüsse erworben, während ich weiterarbeitete. Ich bin in die Welt der Daten eingetreten und habe für öffentliche Einrichtungen und große Unternehmen gearbeitet. Nach zwanzig Jahren Erfahrung bin ich als Anfänger neu gestartet, aber nicht bei null. Ich habe die Fähigkeit mitgebracht, Menschen zu lesen, sie auch ohne Worte zu verstehen. Eine Sensibilität, die man vor einem Bildschirm nicht lernt."),
("Oggi aiuto le piccole attività a semplificare il lavoro attraverso dati e tecnologia, per restituire tempo alle persone, alle famiglie, alle loro passioni. Ho imparato a leggere i numeri per capire le attività, e a leggere le persone per capire cosa conta davvero. È da questo incontro che parto, prima di analizzare, esplorare le possibilità, scegliere e costruire. Con una regola: i numeri che contano sono quelli del cliente. Altrimenti la soluzione sarebbe la mia, non la sua.", "Heute helfe ich kleinen Betrieben, ihre Arbeit durch Daten und Technologie zu vereinfachen, um Menschen, Familien und ihren Leidenschaften Zeit zurückzugeben. Ich habe gelernt, Zahlen zu lesen, um Betriebe zu verstehen, und Menschen zu lesen, um zu verstehen, was wirklich zählt. Von dieser Begegnung gehe ich aus, bevor ich analysiere, Möglichkeiten erkunde, auswähle und baue. Mit einer Regel: Die Zahlen, die zählen, sind die des Kunden. Sonst wäre die Lösung meine, nicht seine."),
# domande
("Prima di scrivere", "Vor der Anfrage"),
("Domande <em>frequenti</em>", "Häufig<br>gestellte<br><em>Fragen</em>"),
("Quanto costa?", "Was kostet es?"),
("Dipende dal lavoro. Dopo il primo incontro arriva un prezzo scritto e chiuso, che non cambia in corsa. Il costo del check-up viene scalato dal lavoro che segue.",
 "Das hängt von der Arbeit ab. Nach dem Erstgespräch kommt ein schriftlicher Festpreis, der sich unterwegs nicht ändert. Die Kosten des Check-ups werden auf die anschließende Arbeit angerechnet."),
("Cosa succede dopo la consegna?", "Was geschieht nach der Übergabe?"),
("Comincia la cura continua: aggiornamenti, correzioni e prima risposta entro un giorno lavorativo. Ogni mese un resoconto mostra le ore usate, le cose fatte e i numeri di andamento.", "Es beginnt die laufende Betreuung: Updates, Korrekturen und eine erste Antwort innerhalb eines Werktags. Jeden Monat zeigt ein Bericht die genutzten Stunden, die erledigten Arbeiten und die Entwicklungszahlen."),
("Quanto tempo serve?", "Wie lange dauert es?"),
("Da pochi giorni per un menu a qualche settimana per un sito completo. Il tempo è scritto nel preventivo e parte dal momento in cui arriva tutto il materiale. Il massimo focus su ogni lavoro è garantito, per una consegna nei tempi scritti.", "Von wenigen Tagen für eine Speisekarte bis zu einigen Wochen für eine vollständige Website. Die Zeit steht im Angebot und beginnt, sobald das gesamte Material eingetroffen ist. Volle Konzentration auf jede Arbeit ist garantiert, für eine Lieferung in der angegebenen Zeit."),
("A chi appartengono dominio e contenuti?", "Wem gehören Domain und Inhalte?"),
("Al cliente, sempre. Dominio, contenuti, dati e accessi sono intestati a lui e, se lo chiede, vengono gestiti per suo conto. Alla fine del rapporto tutto viene consegnato.",
 "Dem Kunden, immer. Domain, Inhalte, Daten und Zugänge laufen auf seinen Namen und werden auf Wunsch in seinem Auftrag verwaltet. Am Ende der Zusammenarbeit wird alles übergeben."),
("Cosa sono le ore incluse nella cura continua?", "Wie funktionieren die Stunden der laufenden Betreuung?"),
("Il tempo mensile dedicato alle richieste: modifiche ai contenuti, interventi ordinari, domande. Aggiornamenti tecnici, sicurezza e backup non lo consumano. Il primo mese è a forfait e senza limite di ore: tutto ciò che è ordinario può rientrare, e cosa includere si decide insieme in base alle esigenze. A fine mese il livello si stabilisce insieme, guardando i dati e le informazioni raccolte. I grandi sviluppi si preventivano a parte.",
 "Die monatliche Zeit für Anfragen: Inhaltsänderungen, laufende Eingriffe, Fragen. Technische Updates, Sicherheit und Backups verbrauchen sie nicht. Der erste Monat ist pauschal und ohne Stundenbegrenzung: Alles Übliche kann dazugehören, und was enthalten ist, wird gemeinsam nach Bedarf entschieden. Am Monatsende wird das Niveau gemeinsam festgelegt, anhand der gesammelten Daten und Informationen. Große Entwicklungen werden separat angeboten."),
("Dove si lavora?", "Wo wird gearbeitet?"),
("Lo studio è a Cesenatico. In Romagna ci si incontra di persona, nel resto d'Italia in video, con lo stesso metodo.",
 "Das Studio ist in Cesenatico. In der Romagna trifft man sich persönlich, im übrigen Italien per Video, mit derselben Methode."),
("Si lavora anche in inglese?", "Wird auch auf Englisch gearbeitet?"),
("Sì, con piena disponibilità: siti, menu, carta dei vini, documenti e assistenza si realizzano in inglese come in italiano.", "Ja, uneingeschränkt: Websites, Speisekarten, Weinkarten, Dokumente und Support entstehen auf Englisch ebenso wie auf Italienisch."),
("Quali dati vengono raccolti?", "Welche Daten werden erhoben?"),
("Solo quelli lasciati scrivendo o richiedendo un incontro, usati per rispondere. Il dettaglio è nell'", "Nur jene, die beim Schreiben oder bei der Terminanfrage hinterlassen werden, verwendet, um zu antworten. Die Einzelheiten stehen in der "),
# chiusura e piede
("Si comincia <em>da un numero</em>", "Es beginnt <em>mit einer Zahl</em>"),
("Modalità", "Format"),
("Il primo incontro si richiede da qui: di persona è la scelta consigliata, in alternativa in video. Data e orario vengono confermati entro un giorno lavorativo.", "Das Erstgespräch wird von hier aus angefragt: Persönlich ist die empfohlene Wahl, alternativ per Video. Datum und Uhrzeit werden innerhalb eines Werktags bestätigt."),
("Conferma in arrivo.", "Bestätigung unterwegs."),
("Conferma di data e orario entro un giorno lavorativo", "Datum und Uhrzeit innerhalb eines Werktags bestätigt"),
("Primo incontro di un'ora, offerto", "Einstündiges Erstgespräch, vom Studio angeboten"),
("Check-up o preventivo scritto, a prezzo chiuso", "Check-up oder schriftliches Angebot zum Festpreis"),
("Bastano pochi dati. Data e orario vengono confermati entro un giorno lavorativo.", "Wenige Angaben genügen. Datum und Uhrzeit werden innerhalb eines Werktags bestätigt."),
("Dubbi? Scrivi su WhatsApp", "Fragen? Per WhatsApp schreiben"),
("Di persona", "Persönlich"),
("Consigliato, a Cesenatico e dintorni", "Empfohlen, in Cesenatico und Umgebung"),
("In video", "Per Video"),
("Dal resto del mondo", "Von überall auf der Welt"),
("Giorni e orari preferiti (facoltativo)", "Bevorzugte Tage und Uhrzeiten (optional)"),
("Richiesta ricevuta", "Anfrage erhalten"),
("Chiudi e torna al sito", "Schließen und zur Seite zurück"),
("Contatti", "Kontakt"),
("Informazioni", "Informationen"),
("Domande frequenti", "Häufige Fragen"),
("Logo in definizione", "Logo in Arbeit"),
("di Matia Zoffoli", "von Matia Zoffoli"),
("Pagina di prova: nome, testi e condizioni sono in bozza.", "Testseite: Name, Texte und Konditionen sind Entwürfe."),
("Studio Matiz di Matia Zoffoli, Cesenatico.", "Studio Matiz von Matia Zoffoli, Cesenatico."),
]

ATTR = [
("Studio Matiz, inizio pagina", "Studio Matiz, Seitenanfang"),
("Principale", "Hauptnavigation"),
("Chiudi", "Schließen"),
("Presenza online", "Online-Präsenz"),
("Automazioni", "Automatisierungen"),
("Cura continua", "Laufende Betreuung"),
("Check-up", "Check-up"),
("Scheda precedente", "Vorherige Karte"),
("Scheda successiva", "Nächste Karte"),
("Stabilimento balneare", "Strandbad"),
("Ristorante o bar", "Restaurant oder Bar"),
("Hotel o struttura ricettiva", "Hotel oder Unterkunft"),
("Negozio o artigiano", "Geschäft oder Handwerksbetrieb"),
("Studio professionale", "Kanzlei oder Praxis"),
("Altro", "Sonstiges"),
("Non ho niente online", "Ich habe nichts online"),
("Ho un sito vecchio", "Ich habe eine veraltete Website"),
("Ho un sito che nessuno segue", "Ich habe eine Website, um die sich niemand kümmert"),
("Ho un sito che funziona", "Ich habe eine funktionierende Website"),
]

WA = [
("Ciao Matia, vorrei saperne di più su: Presenza online", "Hallo Matia, ich würde gern mehr erfahren über: Online-Präsenz"),
("Ciao Matia, vorrei saperne di più su: Automazioni", "Hallo Matia, ich würde gern mehr erfahren über: Automatisierungen"),
("Ciao Matia, vorrei saperne di più su: Cura continua", "Hallo Matia, ich würde gern mehr erfahren über: Laufende Betreuung"),
("Ciao Matia, vorrei saperne di più su: Check-up", "Hallo Matia, ich würde gern mehr erfahren über: Check-up"),
("Ciao Matia, ho un altro obiettivo o problema di cui vorrei parlare.", "Hallo Matia, ich habe ein anderes Ziel oder Problem, über das ich gern sprechen würde."),
("Ciao Matia, vorrei fissare un primo incontro.", "Hallo Matia, ich würde gern ein Erstgespräch vereinbaren."),
("Ciao Matia, ho appena richiesto il primo incontro dal sito.", "Hallo Matia, ich habe soeben das Erstgespräch über die Website angefragt."),
]

JS = [
("['Il problema', 'La risposta']", "['Das Problem', 'Die Antwort']"),
("b[4] === 'settimane'", "b[4] === 'Wochen'"),
("'Pagina singola', 10, 'giorni'", "'Einzelseite', 10, 'Tage'"),
("'Sito completo', 3, 'settimane'", "'Vollständige Website', 3, 'Wochen'"),
("'Sito con funzioni', 6, 'settimane'", "'Website mit Funktionen', 6, 'Wochen'"),
("'Menu digitale', 5, 'giorni'", "'Digitale Speisekarte', 5, 'Tage'"),
("'Automazione semplice', 10, 'giorni'", "'Einfache Automatisierung', 10, 'Tage'"),
("'Automazione articolata', 10, 'giorni'", "'Komplexe Automatisierung', 10, 'Tage'"),
("'Strumento su misura', 5, 'settimane'", "'Maßgeschneidertes Werkzeug', 5, 'Wochen'"),
("'Check-up', 3, 'giorni lavorativi'", "'Check-up', 3, 'Werktage'"),
("\"Manca il tipo di attività.\"", "\"Die Art des Betriebs fehlt.\""),
("\"Manca almeno una voce da scegliere.\"", "\"Mindestens eine Option muss gewählt werden.\""),
("\"Manca la situazione online di oggi.\"", "\"Die aktuelle Online-Situation fehlt.\""),
("\"Manca la dimensione del lavoro.\"", "\"Der Umfang der Arbeit fehlt.\""),
("\"Manca il nome.\"", "\"Der Name fehlt.\""),
("\"L'indirizzo email non è valido.\"", "\"Die E-Mail-Adresse ist nicht gültig.\""),
("'Per vedere il prezzo serve spuntare l\\'informativa privacy.'", "'Um den Preis zu sehen, muss die Datenschutzerklärung angehakt werden.'"),
("b[0] === b[1] ? eur(b[0]) + ' euro' : 'da ' + eur(b[0]) + ' euro'", "b[0] === b[1] ? eur(b[0]) + ' €' : 'ab ' + eur(b[0]) + ' €'"),
("'Il check-up: ' + eur(r.lo) + ' euro' : 'Da ' + eur(r.lo) + ' euro'", "'Der Check-up: ' + eur(r.lo) + ' €' : 'Ab ' + eur(r.lo) + ' €'"),
("'Tempo di consegna: circa ' + r.longest[3] + ' ' + r.longest[4] + ', scritto nel preventivo.'", "'Lieferzeit: ca. ' + r.longest[3] + ' ' + r.longest[4] + ', im Angebot schriftlich festgehalten.'"),
("\"Da dove partire? Il check-up serve a questo: si guarda cosa c'è già e si indica cosa conviene fare per primo. Il costo viene scalato dal lavoro che segue.\"",
 "\"Wo anfangen? Dafür ist der Check-up da: Er schaut sich an, was schon besteht, und zeigt, was zuerst sinnvoll ist. Die Kosten werden auf die anschließende Arbeit angerechnet.\""),
("\"È il prezzo di partenza per il lavoro descritto: la cifra finale dipende da quanto è articolato.\"",
 "\"Das ist der Startpreis für die beschriebene Arbeit: Der Endbetrag hängt davon ab, wie umfangreich sie ist.\""),
("\"Non è un preventivo: il prezzo vero viene scritto dopo il primo incontro e non cambia in corsa. IVA se dovuta.\"",
 "\"Das ist kein Angebot: Der echte Preis wird nach dem Erstgespräch schriftlich festgehalten und ändert sich unterwegs nicht. MwSt., falls fällig.\""),
("|| 'cura continua'", "|| 'laufende Betreuung'"),
("$('#estRange').textContent = eur(CURA[0]) + ' euro il primo mese';", "$('#estRange').textContent = eur(CURA[0]) + ' € im ersten Monat';"),
("'Cura continua, primo mese a forfait', eur(CURA[0]) + ' euro'", "'Laufende Betreuung, erster Monat pauschal', eur(CURA[0]) + ' €'"),
("'Dal secondo mese', 'da ' + eur(CURA[1]) + ' euro al mese'", "'Ab dem zweiten Monat', 'ab ' + eur(CURA[1]) + ' € im Monat'"),
("\"Il forfait copre assistenza, ricerca e idee senza limite di ore, esclusi i nuovi sviluppi. A fine mese un resoconto con le ore reali stabilisce il livello dal secondo mese, con ore extra a 50 euro l'ora.\"",
 "\"Die Pauschale deckt Support, Recherche und Ideen ohne Stundenbegrenzung, ohne neue Entwicklungen. Am Monatsende legt ein Bericht mit den tatsächlichen Stunden das Niveau ab dem zweiten Monat fest, Zusatzstunden zu 50 Euro pro Stunde.\""),
("\"La cura continua si aggiunge al prezzo del lavoro: il primo mese è a forfait e senza limite di ore, poi il livello si decide sulle ore reali.\"",
 "\"Die laufende Betreuung kommt zum Preis der Arbeit hinzu: Der erste Monat ist pauschal und ohne Stundenbegrenzung, danach wird das Niveau anhand der tatsächlichen Stunden festgelegt.\""),
("lingua: 'it',", "lingua: 'de',"),
("'Ciao Matia, ho visto dal sito un prezzo di partenza (' + $('#estRange').textContent + ') per: ' + nomi + '. Attività: ' + val('tipo') + '. Vorrei parlarne.'",
 "'Hallo Matia, ich habe auf der Website einen Startpreis gesehen (' + $('#estRange').textContent + ') für: ' + nomi + '. Betrieb: ' + val('tipo') + '. Ich würde gern darüber sprechen.'"),
("\"Registrazione della richiesta in corso...\"", "\"Anfrage wird gespeichert...\""),
("\"Per inviare la richiesta serve spuntare l'informativa privacy.\"", "\"Um die Anfrage zu senden, muss die Datenschutzerklärung angehakt werden.\""),
("\"Invio della richiesta in corso...\"", "\"Anfrage wird gesendet...\""),
("\"Richiesta ricevuta. La prima risposta arriva entro un giorno lavorativo.\"", "\"Anfrage erhalten. Die erste Antwort kommt innerhalb eines Werktags.\""),
("\"La richiesta non è stata registrata. Un messaggio su WhatsApp o una email arrivano comunque.\"", "\"Die Anfrage wurde nicht gespeichert. Eine WhatsApp-Nachricht oder eine E-Mail kommt trotzdem an.\""),
]

HEADS = [
('<html lang="it" class="pending">', '<html lang="de" class="pending">'),
("<title>Studio Matiz - Soluzioni su misura</title>", "<title>Studio Matiz - Nach Maß</title>"),
('content="Progettazione e sviluppo di siti, automazioni e strumenti digitali per piccole imprese. Il primo incontro è offerto dallo studio."',
 'content="Entwurf und Entwicklung von Websites, Automatisierungen und digitalen Werkzeugen für kleine Betriebe. Das Erstgespräch wird vom Studio angeboten."'),
('src="assets/', 'src="/assets/'),
('href="privacy.html"', 'href="/de/privacy.html"'),
('<span class="flag flag--it"></span><span>IT</span>', '<span class="flag flag--de"></span><span>DE</span>'),
('<a href="/" lang="it" aria-current="true"><span', '<a href="/" lang="it"><span'),
('<a href="/de/" lang="de" hreflang="de"><span', '<a href="/de/" lang="de" hreflang="de" aria-current="true"><span'),
('aria-label="Lingua"', 'aria-label="Sprache"'),
]

if __name__ == "__main__":
    b.build(TEXT, ATTR, WA, JS, HEADS, OUT)
